version: '3'

services:
    flask:
      container_name: flask
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - 5002:5002
      networks:
        - network

networks:
  network: